name: Deploy to VM

on:
  push:
    branches: [ "main" ]  # or master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install rsync & ssh
        run: sudo apt-get update && sudo apt-get install -y rsync openssh-client

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ws.icefish.dev >> ~/.ssh/known_hosts

      - name: Sync files
        run: |
          rsync -az --delete ./ deploy@ws.icefish.dev:/var/www/portfolio/
